apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zuul
  namespace: basic-app
  labels:
    app: zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul
  template:
    metadata:
      labels:
        app: zuul
    spec:
      serviceAccountName: application
      containers:
        - image: yinbucheng/zuul:v1.0.0
          env:
            - name: SERVICE_NAME
              value: server-b
          imagePullPolicy: IfNotPresent
          name: zuul
          securityContext:
            allowPrivilegeEscalation: True
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
            tcpSocket:
              port: 7070
          ports:
            - containerPort: 7070
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: zuul
  namespace: basic-app
  labels:
    app: zuul
spec:
  type: NodePort
  selector:
    app: zuul
  ports:
    - name: port1    #暴露的端口一的名称
      protocol: TCP
      nodePort: 32400 #对外暴露的端口
      port: 7070       #servic暴露端口
      targetPort: 7070 #pod目标端口