apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-server
  namespace: basic-app
  labels:
    app: zipkin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-server
  template:
    metadata:
      labels:
        app: zipkin-server
    spec:
      serviceAccountName: application
      containers:
        - image: yinbucheng/zipkin-server:v1.0.0
          env:
            - name: SERVICE_NAME
              value: zipkin-server
          imagePullPolicy: IfNotPresent
          name: zipkin-server
          securityContext:
            allowPrivilegeEscalation: True
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
            tcpSocket:
              port: 6090
          ports:
            - containerPort: 6090
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-server
  namespace: basic-app
  labels:
    app: zipkin-server
spec:
  type: NodePort
  selector:
    app: zipkin-server
  ports:
    - name: port1    #暴露的端口一的名称
      protocol: TCP
      nodePort: 32413 #对外暴露的端口
      port: 6090       #servic暴露端口
      targetPort: 6090 #pod目标端口